#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-shapefiles
Version  : 0.7.2
Release  : 42
URL      : https://cran.r-project.org/src/contrib/shapefiles_0.7.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/shapefiles_0.7.2.tar.gz
Summary  : Read and Write ESRI Shapefiles
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -n shapefiles
cd %{_builddir}/shapefiles

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661446028

%install
export SOURCE_DATE_EPOCH=1661446028
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/shapefiles/DESCRIPTION
/usr/lib64/R/library/shapefiles/INDEX
/usr/lib64/R/library/shapefiles/Meta/Rd.rds
/usr/lib64/R/library/shapefiles/Meta/features.rds
/usr/lib64/R/library/shapefiles/Meta/hsearch.rds
/usr/lib64/R/library/shapefiles/Meta/links.rds
/usr/lib64/R/library/shapefiles/Meta/nsInfo.rds
/usr/lib64/R/library/shapefiles/Meta/package.rds
/usr/lib64/R/library/shapefiles/NAMESPACE
/usr/lib64/R/library/shapefiles/R/shapefiles
/usr/lib64/R/library/shapefiles/R/shapefiles.rdb
/usr/lib64/R/library/shapefiles/R/shapefiles.rdx
/usr/lib64/R/library/shapefiles/help/AnIndex
/usr/lib64/R/library/shapefiles/help/aliases.rds
/usr/lib64/R/library/shapefiles/help/paths.rds
/usr/lib64/R/library/shapefiles/help/shapefiles.rdb
/usr/lib64/R/library/shapefiles/help/shapefiles.rdx
/usr/lib64/R/library/shapefiles/html/00Index.html
/usr/lib64/R/library/shapefiles/html/R.css
